apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/theepicsaxguy/homelab'
        revision: HEAD
        directories:
          - path: k8s/apps/*
          - path: k8s/infra/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      # Optionally, you can route based on the directory structure (for example, use different AppProjects)
      project: '{{ if contains "infra" path }}infrastructure{{ else }}applications{{ end }}'
      source:
        repoURL: 'https://github.com/theepicsaxguy/homelab'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
