apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: common-env
    namespace: lldap
    literals:
      - TZ="Europe/Oslo"
      - GID="1001"
      - UID="1001"
  - name: lldap-config
    namespace: lldap
    literals:
      - LLDAP_HTTP_URL="https://lldap.pc-tips.se"
      - LLDAP_LDAPS_OPTIONS__ENABLED="true"
      - LLDAP_LDAPS_OPTIONS__CERT_FILE="/cert/tls.crt"
      - LLDAP_LDAPS_OPTIONS__KEY_FILE="/cert/tls.key"
  - name: bootstrap-env
    namespace: lldap
    literals:
      - LLDAP_URL="http://lldap:80"
      - LLDAP_ADMIN_USERNAME="admin"
      - DO_CLEANUP="true"

resources:
  - ns.yaml
  - svc.yaml
  - cnpg-db.yaml
  - cert.yaml
  - lldap-credentials.yaml
  - lldap-config.yaml
  - smtp-credentials.yaml
  - deployment.yaml
  - http-route.yaml
  - bootstrap.yaml
