apiVersion: v1
kind: Service
metadata:
  name: whoami
  annotations:
    io.cilium/lb-ipam-ips: 192.168.10.225
spec:
  type: LoadBalancer
  selector:
    app: whoami
  ports:
    - name: web
      port: 80
      targetPort: http
