apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: agent-config
    namespace: netbird
    literals:
      - NB_HOSTNAME="talos-agent"
      - NB_LOG_LEVEL="warn"
      - NB_MANAGEMENT_URL="https://netbird.pc-tips.se"
      - NB_ADMIN_URL="https://netbird.pc-tips.se"
      - NB_CONFIG="/var/lib/netbird/config.json"

resources:
  - agent-setup-key.yaml
  - daemon-set.yaml
