apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-backend
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: dex.authentik.clientSecret
      remoteRef:
        key: 4dc7eda0-f685-4118-ba14-b2e8000e793b
    - secretKey: dex.authentik.clientId
      remoteRef:
        key: eb447b09-04d5-421f-b32a-b2e8000e5dc3
