apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: turnserver-config
    namespace: coturn
    files:
      - config/turnserver.conf
  - name: coturn-config
    namespace: coturn
    literals:
      - LISTENING_IP="0.0.0.0"
      - LISTENING_PORT="3478"
      - TLS_LISTENING_PORT="5349"
      - REALM="coturn.pc-tips.se"

resources:
  - ns.yaml
  - deployment.yaml
  - cert.yaml
  - svc.yaml
  - netbird-credentials.yaml
