apiVersion: v1
kind: Service
metadata:
  name: web
  annotations:
    io.cilium/lb-ipam-ips: 192.168.10.230
spec:
  selector:
    app: karakeep-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
