apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: adguard-users-auth
  namespace: dns
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: adguard-users-auth
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
spec:
  organizationId: '4a014e57-f197-4852-9831-b287013e47b6'
  secretName: adguard-users
  map:
    - bwSecretId: '3f81c048-3f10-4c57-a03b-b2890117f98d'
      secretKeyName: 'users.conf'
  authToken:
    secretName: bw-auth-token
    secretKey: token
