apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: controllers
  namespace: argocd
  labels:
    dev.pc-tips: controllers
spec:
  description: Project for core infrastructure controllers
  sourceRepos:
    - 'https://github.com/masonfx/homelab'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
